version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: infra/scripts/copy_nginx_config.sh
      timeout: 120
      runas: root
#    - location: infra/scripts/install_datadog_agent.sh
#      timeout: 120
#      runas: root
  ApplicationStart:
    - location: infra/scripts/run_new_was.sh
      timeout: 120
      runas: ec2-user
#    - location: infra/scripts/health_check.sh
#      timeout: 120
#      runas: ec2-user
#    - location: infra/scripts/switch.sh
#      timeout: 120
#      runas: ec2-user
#    - location: infra/scripts/stop_old_was.sh
#      timeout: 120
#      runas: ec2-user
