version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: infra/scripts/setup_nginx.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: infra/scripts/start_application.sh
      timeout: 120
      runas: ec2-user
