name: deploy-prod-onemoretang-server

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      profile: prod
      module_name: onemoretang-server
      s3_bucket_name: onemoretang-codedeploy-artifacts
    secrets: inherit
